### ISSUE TITLE
Who's using Athens in production?

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#1323]
We have been working on making Athens production ready and as we get closer to v1, we'd love to know who's using Athens within their organizations. 

I'll go first: The New York Times :)

**Comment by arschles** [comment]
athens.azurefd.net (hopefully behind another domain soon, if I get some free time!)

**Comment by leitzler** [comment]
I do, at work :)

**Comment by johnjelinek** [comment]
The Container Store

**Comment by arschles** [comment]
@johnjelinek thanks for letting us know! I can't resist posting this because I love the slogan...

![contain yourself](https://images.containerstore.com/catalogimages/113423/TCSreusableTote_x.jpg)

**Comment by srimaln91** [comment]
We are using Athens in production

**Comment by awkj** [comment]
As far as I know, Xiaomi Company is using it .

**Comment by arschles** [comment]
@srimaln91 can you let us know who "We" is 😁 ?

**Comment by arschles** [comment]
@leitzler can you let us know where "Work" is 😁 ?

**Comment by johnjelinek** [comment]
@arschles: maybe it's WeWork?

**Comment by srimaln91** [comment]
@arschles `PickMe`. A taxi-hailing company operating in Sri Lanka

**Comment by seeruk** [comment]
Icelolly.com are using it in production. 

The main barrier we've hit is the old versions of the Helm Charts being deleted - we have some automation set up for installing things in our K8s clusters, and we've had to mirror the chart so we don't have to keep upgrading it all of the time. It'd be nice to be able to rely on older versions of the Chart existing in the official repo.

**Comment by arschles** [comment]
@seeruk The old versions of the Helm Charts being deleted is a bug! Would you mind filing an issue for that? We have a script that uploads charts every time a release is cut, and it must be overwriting old stuff instead of just adding new stuff

**Comment by seeruk** [comment]
@arschles I've submitted a PR fixing the cause of the issue here: https://github.com/gomods/drone-helm/pull/1/files

**Comment by arschles** [comment]
@seeruk thanks! I just merged it 😄

**Comment by utrack** [comment]
OZON.ru - russian e-commerce :)

**Comment by daxmc99** [comment]
Rancher Labs 🐮

**Comment by ernado** [comment]
We are using Athens at Mail.ru (Russian IT Corp), really helps with private modules.

**Comment by arschles** [comment]
@ernado glad to hear it! And thanks for your contributions 😄

**Comment by linzhp** [comment]
We are using a private fork of Athens at Uber. We wish to contribute to the project and make it more flexible and extensible (e.g., #1511), so we don't have to maintain a private fork.

**Comment by arschles** [comment]
@linzhp I'm glad that Athens seems to be working for you! I'll check out #1511 as soon as I can

**Comment by duedal** [comment]
Unity.com (video game engine etc) is using Athens, as a recent hire at Unity, I was frustrated with the use of vendoring, so I was happy when I found Athens to help me get rid of it.

Our primary reason for using Athens is to provide access to private go modules, so I put athens behind an envoy proxy with custom authentication, for easy use with the various different CI solutions we run at Unity.

**Comment by krishnakumar4a4** [comment]
We do use it at work too. Unfortunately, for us, athens is running on a VM without internet access(some policy limitations). Whenever we need a new third party module from internet, I enable internet through HTTP proxy + SSH reverse tunnel from a machine with internet. Crazy, but better than copying modules from somewhere else to athens storage.

**Comment by arschles** [comment]
@krishnakumar4a4 your use case is one that we've had in mind for a while. I'm glad to hear that it's working for you

**Comment by stackedsax** [comment]
@marwan-at-work We use it in production at [G-Research](https://github.com/G-Research).  Our whole Go developer experience relies on it.  

We love it, but we ran into one issue that caused us some pain: https://github.com/gomods/athens/issues/1512.  We fixed this for us internally, so now we're using an internal fork... which I hate.  I'll push the team to work with y'all to upstream a fix so we can be more up-to-date and involved in the community.

**Comment by marwan-at-work** [comment]
@stackedsax ah, i haven't checked out #1512 before. But that sounds great.

**Comment by abhay-krishna** [comment]
[Amazon EKS Distro!](https://github.com/aws/eks-distro)

**Comment by prologic** [comment]
I do for my self-hosted infra. Not that happy with the memory usage though. I run it in a Docker Swarm cluster with the following resource constriants:

```#!yaml
      resources:
        reservations:
          cpus: "1.0"
          memory: 256M
        limits:
          cpus: "2.0"
          memory: 512M
```

And the memory and cpu usage are still not that happy. Admittedly this is probably due to large dependencies being cached and cached.

<img width="1190" alt="Screen Shot 2022-08-11 at 14 58 18" src="https://user-images.githubusercontent.com/1290234/184067293-3e58a10e-0421-46ae-99af-8afae6009be2.png">
<img width="1197" alt="Screen Shot 2022-08-11 at 14 58 34" src="https://user-images.githubusercontent.com/1290234/184067301-4b98d6cc-3ead-4157-9221-a01b7d5a7b06.png">

**Comment by uhthomas** [comment]
[Cloudflare](https://www.cloudflare.com/) has recently started using Athens internally.

**Comment by hanzo** [comment]
We use Athens in production at [Lyft](https://www.lyft.com/). For the most part it has worked quite well for us, although we've been seeing slower performance after upgrading the docker container where we run Athens from Go 1.22 to 1.23. Has anyone else noticed this?
